name: Prod Deploy (Latest Release)

env:
  AZURE_WEBAPP_NAME: opt-pro-prod

on:
  workflow_dispatch:
    inputs:
      release-sha:
        description: 'Latest Release SHA'
        required: true

permissions:
  contents: read

jobs:
  setup:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    outputs:
      input-tag: ${{ steps.latest-tag-by-commitsha.outputs.tag_name }}
      latest-tag: ${{ steps.latest-release.outputs.tag}}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: keiguard/github-actions-test
          token: ${{ secrets.PAT_DEV }}
          ref: ${{ github.event.inputs.release-sha }}
          
      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
        
      - name: Get latest release tag
        id: latest-release
        run: echo "tag=$(git tag --sort=committerdate | grep -E '^v[0-9]' | tail -1)" >> $GITHUB_OUTPUT

      - uses: cardinalby/git-get-release-action@1.2.4
        id: latest-tag-by-commitsha
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commitSha: ${{ github.event.inputs.release-sha }}
          
      - name: Debug outputs
        run: |
          echo "Latest release tag: ${{ steps.latest-release.outputs.tag }}"
          echo "Latest tag by commit sha: ${{ steps.latest-tag-by-commitsha.outputs.tag_name }}"
          echo "Input tag: ${{ steps.latest-tag-by-commitsha.outputs.tag_name }}"
        
  deploy:
    if: ${{ needs.setup.outputs.input-tag == needs.setup.outputs.latest-tag }}
    runs-on: ubuntu-latest
    needs: setup
    permissions:
      contents: none
    environment:
      name: Production
    steps:
      - name: Test logic
        run: echo "${{ needs.setup.outputs.input-tag == needs.setup.outputs.latest-tag }}"